version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install numpy==1.21.2
            pip install biopython==1.78

      - run:
          name: temp style
          command: |
            . venv/bin/activate
            pip install pycodestyle
            pycodestyle --ignore=E501,E203,E731,W503,W292 *.py */*py

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pip install nose
            nosetests -v


      - store_artifacts:
          path: test-reports
          destination: test-reports
